scldeps.sh: read all the files from stdin
Based on [1], the script should read all the lines from stdin and
process them.  We don't need this functionality, though not
processing whole the stdin means that SIGPIPE is (might be) thrown
by kernel.

On Fedora 27, SIGPIPE caused rpmbuild's exit status 141, and no
useful error output was thrown out:

  Processing files: sclo-postgresql96-3.0-2.fc27.x86_64
  Processing files: sclo-postgresql96-runtime-3.0-2.fc27.x86_64
  Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.2X52o3
  + umask 022
  + cd /builddir/build/BUILD
  + cd sclo-postgresql96-3.0
  + DOCDIR=/builddir/build/BUILDROOT/sclo-postgresql96-3.0-2....
  + export DOCDIR
  + /usr/bin/mkdir -p /builddir/build/BUILDROOT/sclo-postgres...
  + cp -pr README /builddir/build/BUILDROOT/sclo-postgresql96...
  + cp -pr LICENSE /builddir/build/BUILDROOT/sclo-postgresql9...
  + exit 0
  ERROR: Exception(intermediate-srpm/sclo-postgresql96-3.0-2....
  INFO: Results and/or logs in: /var/lib/copr-builder/results
  INFO: Cleaning up build root ('cleanup_on_failure=True')
  Start: clean chroot
  INFO: unmounting tmpfs.
  Finish: clean chroot
  ERROR: Command failed. See logs for output.

Also fix shell bug in "$@" processing.

[1] http://rpm.org/user_doc/dependency_generators.html